### ISSUE TITLE
operator.attrgetter/itemgetter is not supported by signature

### ISSUE THREAD

**Issue by seeM** [wesselb/plum#43]
Hi there 👋 I'm back with another issue 😄 Here's a reproducible example:

```python
from operator import attrgetter
from plum import Function
f = Function(lambda x: x)
pf = Function(f)
g = attrgetter('a')  # same holds for operator.itemgetter
g = pf.dispatch(g)
g(0)
```
```pytb
ValueError: callable operator.attrgetter('a') is not supported by signature
```

It might be possible for us to implement a workaround on our side but it would be great if it were handled by `plum`. My thinking, which isn't very elegant, is to wrap it in another callable that passes through and to set that callable's `__signature__`, which `inspect.signature` uses as a sort of cache. I haven't tested that yet.

cc @wesselb

---

For completeness, the following also fails with a different error, but isn't a use-case for us atm so less crucial:

```python
from operator import attrgetter
from plum import dispatch
f = attrgetter('a')
pf = dispatch(f)
```
```pytb
AttributeError: 'operator.attrgetter' object has no attribute '__qualname__'
```

**Comment by wesselb** [comment]
@seeM For the first example, my interpretation is that `operator.attrgetter("a")` should be equivalent to `lambda x: operator.attrgetter("a")(x)`, and `inspect.signature` should work for the latter, so that should work

For the second example, I'm not entirely sure what the intention of that code would be. Namely, `attrgetter` can be interpreted as a shorthand for an anonymous function. Anonymous functions don't have names, so I'm not sure that applying `dispatch` to it makes sense, because `dispatch` doesn't know which function it is implementing a method for. I'm therefore tempted to leave the second example error. What are your thoughts on this?

**Comment by seeM** [comment]
@wesselb agreed on point 1.

Point 2 is tricky because we don't actually have a use-case for it, so this is all in the abstract. That said, it's worth noting that `lambda`s do have a name (`<lambda>`) therefore do work by default with `plum`. So I could imagine that `plum` could assume a name like `<attrgetter('a')>` as well. But again, we aren't using it like this so no pressure from us to support that :)

**Comment by wesselb** [comment]
This should not work in `v1.5.16`!

**Comment by wesselb** [comment]
Happy to hear that! :)
